### ISSUE TITLE
请问java中怎样使调用的音频文件在打包成jar包后依然有效

### ISSUE THREAD

**Issue by Netsh-f** [buaa-soft-summer/soft-summer-2022#24]
使用的java8，我需要添加游戏的背景音乐。目前方案是使用 javax.sound.sampled.*  java.io.*包获取音频

    private void prefetch() {
        try {
            //获取音频输入流
            audioStream = AudioSystem.getAudioInputStream(new File(musicPath));
            //获取音频的编码对象
            audioFormat = audioStream.getFormat();
            //包装音频信息
            DataLine.Info dataLineInfo = new DataLine.Info(SourceDataLine.class,
                    audioFormat, AudioSystem.NOT_SPECIFIED);
            //使用包装音频信息后的Info类创建源数据行，充当混频器的源
            sourceDataLine = (SourceDataLine) AudioSystem.getLine(dataLineInfo);

            sourceDataLine.open(audioFormat);
            sourceDataLine.start();

        } catch (UnsupportedAudioFileException ex) {
            ex.printStackTrace();
        } catch (LineUnavailableException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

在IDEA中运行正常，音频资源放在了同包下的resources文件夹中，并通过test.class.getClassLoader().getResource("music/startMusic1.wav").getPath()
来获取路径。
但在打包后音频不能正常播放，并出现

java.io.FileNotFoundException: file:\D:\ideaProject\Orlog\out\artifacts\Orlog_jar\Orlog.jar!\music\startMusic2.wav (文件名、目录名或卷标语法不正确。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.desktop/com.sun.media.sound.SunFileReader.getAudioInputStream(SunFileReader.java:117)
        at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1060)
        at com.zwj.MusicPlayer.playMusic(MusicPlayer.java:92)
        at com.zwj.MusicPlayer.playMusic(MusicPlayer.java:68)
        at com.zwj.MusicPlayer.access$000(MusicPlayer.java:7)
        at com.zwj.MusicPlayer$1.run(MusicPlayer.java:138)
        at java.base/java.lang.Thread.run(Thread.java:833)

这样的异常信息
不清楚是获取路径的方式不对，还是播放音频的方法有问题
希望可以找到一种方法在java项目中播放音频，并打包后依然有效

**Comment by jongjyh** [comment]
https://blog.csdn.net/l903445981/article/details/104132107 试试这种解决方案

**Comment by Netsh-f** [comment]
感谢助教答疑，但问题没有解决
我看了这篇文章，并进行了尝试
对于方法一，我使用的是IDEA而非eclipse，我不知道是不是这个原因，在目录下并没有bin文件夹，所以方法一暂时无法解决问题
对于方法二，我创建了Clip类并使用了文章中的方法，并没有达到预期效果，没有异常报错，但在IDEA中运行就没有声音
我不知道是什么原因导致，还请助教解答

**Comment by woarthur** [comment]
我的建议是先用绝对路径，看看是不是路径出了问题，排除掉路径的问题之后再考虑是不是音频的问题

**Comment by Netsh-f** [comment]
感谢助教解答，问题已经解决，方法如下
在项目文件夹中创建sound文件夹，而非src包中
将音频放入sound文件夹
使用String path = new URL("file:sound//startMusic1.wav").getPath();获得路径
打包后将sound放在jar包同一文件夹下
即可解决问题
